"""lixical mistake in discription

Revision ID: 5cf3a32bf08c
Revises: de9396915320
Create Date: 2026-08-29 02:13:15.459080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf3a32bf08c'
down_revision: Union[str, Sequence[str], None] = 'de9396915320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('collections', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('discription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'description')
    # ### end Alembic commands ###
