"""name of collections is not unique

Revision ID: 1bd38c08c6df
Revises: 5cf3a32bf08c
Create Date: 2026-08-31 17:15:13.618486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd38c08c6df'
down_revision: Union[str, Sequence[str], None] = '5cf3a32bf08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    # ### end Alembic commands ###
