"""add request id to query history

Revision ID: ae59246e8aec
Revises: 98c16b377968
Create Date: 2026-09-25 20:43:04.195456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae59246e8aec'
down_revision: Union[str, Sequence[str], None] = '98c16b377968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('request_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_query_history_request_id'), 'query_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_request_id'), table_name='query_history')
    op.drop_column('query_history', 'request_id')
    # ### end Alembic commands ###
