"""lixical mistake in discription

Revision ID: de9396915320
Revises: f052e15efef5
Create Date: 2026-08-29 02:09:35.428261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9396915320'
down_revision: Union[str, Sequence[str], None] = 'f052e15efef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('discription', sa.Text(), nullable=True))
    op.drop_column('collections', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('collections', 'discription')
    # ### end Alembic commands ###
